apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-app
  labels: 
    app: devops-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devops-app
  template:
    metadata:
      labels:
        app: devops-app
    spec:
      containers:
      - name: myntra
        image: ghandgevikas/devopsexamapp:latest
        ports:
        - containerPort: 3000   # Use port 3000
