apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: ghandgevikas/devops-exam-flask:latest
        imagePullPolicy: Always   # <-- Important line
        env:
        - name: MYSQL_HOST
          value: mysql
        - name: MYSQL_USER
          value: root
        - name: MYSQL_PASSWORD
          value: rootpass
        - name: MYSQL_DATABASE
          value: devops_exam
        ports:
        - containerPort: 5000

