apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-canary
spec:
  replicas: 1   # Canary gets only 1 pod
  selector:
    matchLabels:
      app: flask
      version: canary
  template:
    metadata:
      labels:
        app: flask
        version: canary
    spec:
      containers:
      - name: flask
        image: ghandgevikas/devops-exam-flask:latest   # Canary version
        imagePullPolicy: Always
        env:
        - name: MYSQL_HOST
          value: mysql
        - name: MYSQL_USER
          value: root
        - name: MYSQL_PASSWORD
          value: rootpass
        - name: MYSQL_DATABASE
          value: devops_exam
        ports:
        - containerPort: 5000
