apiVersion: v1
kind: Service
metadata:
  name: devops-service
spec:
  selector:
    app: devops-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80            # External port
      targetPort: 5000    # Container port where Flask is running
