apiVersion: v1
kind: Service
metadata:
  name: exam-service
  labels:
    app: exam
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000  # Replace with the port your app runs on
  selector:
    app: exam
